### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Fox32** [google/test_runner.dart#6]
I was thinking to build something like this in the last day, but luckily I found Dart Test Runner. Seems promising, and I look forward for a version that supports Windows.

Looks like the main problem is the detection of the binaries using `which`? Replacing it with `for %G in (pub.bat) do @echo.%~$PATH:G` on Windows seems to be already sufficient (requires runInShell: true). The problem is that you need to know the extension of executable. While `pub` and `dart2js` use batch files  (`bat`)  on Windows, is `content_shell` an executable (`exe`). Either one checks for both `exe` and `bat` extension or passes the expected Windows extension to the `_checkBinary` method. Not sure which one to choose?

In addition, I found a problem expecting the path seperator to be `/`:
```
  String get testFileName {
    String absFilePath = new File(testFilePath).resolveSymbolicLinksSync();
    String absDirPath = dartProject.testDirectory.resolveSymbolicLinksSync();
    // Current code:
    return absFilePath.replaceFirst("$absDirPath/", "");
    // Can be replaced with:
    return absFilePath.replaceFirst("$absDirPath${Platform.pathSeparator}", "");
  }
```
Maybe using the ``path` package can resolve these sort of problem.

I can send a PR adding support for Windows.

**Comment by Fox32** [comment]
Then we can close this, too :)

**Comment by nicolasgarnier** [comment]
Thanks! Would you mind adding Content Shell install instructions for Windows? I've created a section specific to Content Shell in the docs because installing and finding it has been an issue for lots of people:

https://github.com/google/test_runner.dart#content-shell

If you know how to fill the Windows section don't hesitate! :) (You can have a look at the Mac OSX section which I've just filled)

**Comment by Fox32** [comment]
Would be something like:
* Download and unpack into a folder
* Add that folder to PATH

I don't think that this is a good way, but the only I'm aware of. Not sure if there is any tool to make that easier. 

A ```pub global activate content_shell``` would be nice and easy :smile:, is platform independent and solves the PATH problem. But that would be a feature request for the Dart team.

**Comment by nicolasgarnier** [comment]
Yes that's great. I just wasn't sure it was that easy :) (in mac for some reasons and in some cases we need to create an intermediary shell script rather than a soft link... also the name of the executable on Mac: "Content Shell" is different to what's done on other platform "content_shell")

Maybe you can add the instruction/command about how to add a folder to the PATH (just to be thorough... even if that's easy).

**Comment by nicolasgarnier** [comment]
`pub global activate` would be nice but unfortunately it only works for Dart project (right now :))
